<div class="col-md-12">
    <div class="page-header clearfix">
        <h2 class="pull-left">student Details</h2>
        <a href="<?=$this->url('aluno',['action'=>'add'])?>" class="btn btn-success pull-right" role="button">Add New Student</a>
    </div>
	<div class="table-responsive">
		<table id="user-table" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
	 		<thead>
	 			<th>ID</th>
	 			<th>First Name</th>
	 			<th>Last Name</th>
	 			<th>Email</th>
	 			<th>Action</th>
	 		</thead>
                        <tbody>
                            <?php
                            foreach ($alunos as $aluno):
                            ?>
                                <tr>
                                    <td><?=$aluno->getIdAluno()?></td>
                                    <td><?=$aluno->getFirstName()?></td>
                                    <td><?=$aluno->getLastName()?></td>
                                    <td><?=$aluno->getEmail()?></td>
                                    <td>
                                        <!--
                                        <a href="<?=$this->url('aluno',['action'=>'edit', 'id'=>$aluno->getIdAluno()])?>" class="btn btn-link" >Edit</a> 
                                        <a href="<?=$this->url('aluno',['action'=>'delete', 'id'=>$aluno->getIdAluno()])?>" class="btn-link-danger" >Delete</a>
                                        -->
                                        <a href="<?=$this->url('aluno',['action'=>'edit', 'id'=>$aluno->getIdAluno()])?>" class="btn btn-link" ><i class="glyphicon glyphicon-edit"></i></a> 
                                        <a href="<?=$this->url('aluno',['action'=>'delete', 'id'=>$aluno->getIdAluno()])?>" class="btn-link-danger" ><i class="glyphicon glyphicon-trash"></i></a>
                                    </td>
                                </tr>
                            <?php
                            endforeach;
                            ?>
                        </tbody>
		</table>
	</div>    
</div>