<div class="col-md-12">
    <div class="page-header clearfix">
        <h2 class="pull-left">student Details</h2>
        <a href="<?=$this->url('aluno',['action'=>'add'])?>" class="btn btn-success pull-right" role="button">Add New Student</a>
    </div>
	<div class="table-responsive">
		<table id="user-table" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
	 		<thead>
	 			<th>ID</th>
	 			<th>First Name</th>
	 			<th>Last Name</th>
	 			<th>Email</th>
	 			<th>Action</th>
	 		</thead>
                        <tbody>
                            <?php
                            if(sizeof($this->paginator)):
                                
                            foreach ($paginator as $aluno):
                                
                            ?>
                                <tr>
                                    <td><?=$aluno[idaluno]?></td>
                                    <td><?=$aluno[firstname]?></td>
                                    <td><?=$aluno[lastname]?></td>
                                    <td><?=$aluno[email]?></td>
                                    <td>
                                        <!--
                                        <a href="<?=$this->url('aluno',['action'=>'edit', 'id'=>$aluno[idaluno]])?>" class="btn btn-link" >Edit</a> 
                                        <a href="<?=$this->url('aluno',['action'=>'delete', 'id'=>$aluno[idaluno]])?>" class="btn-link-danger" >Delete</a>
                                        -->
                                        <a href="<?=$this->url('aluno',['action'=>'edit', 'id'=>$aluno[idaluno]])?>" class="btn btn-link" ><i class="glyphicon glyphicon-edit"></i></a> 
                                        <a href="<?=$this->url('aluno',['action'=>'delete', 'id'=>$aluno[idaluno]])?>" class="btn-link-danger" ><i class="glyphicon glyphicon-trash"></i></a>
                                    </td>
                                </tr>
                            <?php
                            endforeach;
                            ?>
                            <?php else: ?>
                                <tr>
                                    <td>Nenhum Aluno cadastrado.</td>
                                </tr>
                            <?php endif; ?>
                        </tbody>
		</table>
	</div>    
</div>

<ul>

<?php

echo $this->paginationControl($this->paginator,
 'Sliding',
 '/script/pagination.phtml'); ?>